# Generated by Django 3.0.8 on 2020-10-03 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('topic', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
                ('date_published', models.DateField(auto_now=True)),
                ('scientific_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular article in the database', primary_key=True, serialize=False)),
                ('external_url', models.URLField()),
                ('status', models.CharField(blank=True, choices=[('u', 'unprocessed'), ('p', 'processed without scientific rate'), ('s', 'processed with a scientific rate')], default='u', help_text='Whether the link is stored as a processed article', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sim_rate',
            fields=[
                ('pair_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the article pair', primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('article1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article1', to='sim_rating.Article')),
                ('article2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article2', to='sim_rating.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim_rating.Link'),
        ),
    ]
