# Generated by Django 3.0.8 on 2020-10-03 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim_rating', '0003_auto_20201003_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='topic',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim_rating.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
