# Generated by Django 3.0.8 on 2020-11-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_rating', '0006_auto_20201022_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim_rate',
            name='user_id',
            field=models.CharField(help_text='User ID', max_length=30, null=True),
        ),
    ]
